DROP TABLE IF EXISTS huya_live_info;

CREATE TABLE huya_live_info
(
  uid                  BIGINT PRIMARY KEY NOT NULL,
  sex                  TINYINT(1)         NOT NULL,
  game_full_name       VARCHAR(30)        NOT NULL,
  game_host_name       INTEGER(11)        NOT NULL,
  start_time           DATETIME,
  activity_id          INTEGER(11),
  level                INTEGER(11),
  total_count          INTEGER(11),
  room_name            VARCHAR(100)       NOT NULL,
  is_secret            TINYINT(1),
  camera_open          TINYINT(1),
  live_channel         VARCHAR(15),
  buss_type            INTEGER(11),
  yyid                 VARCHAR(15),
  screenshot           VARCHAR(200)       NOT NULL,
  activity_count       INT(11)            NOT NULL,
  private_host         VARCHAR(20),
  recommend_status     VARCHAR(15),
  nick                 VARCHAR(40),
  short_channel        INTEGER(11),
  avatar180            VARCHAR(200),
  gid                  INTEGER(11),
  channel              BIGINT,
  introduction         VARCHAR(100),
  profile_home_host    VARCHAR(20),
  live_source_type     INTEGER(11),
  screen_type          INTEGER(11),
  bit_rate             INTEGER(11),
  game_type            INTEGER(11),
  attendee_count       INTEGER(11),
  multi_stream_flag    VARCHAR(10),
  codec_type           INTEGER(11),
  live_compatible_flag VARCHAR(11),
  profile_room         INTEGER(11),
  live_id              BIGINT,
  rank_label           VARCHAR(10),
  live_host            VARCHAR(20),
  avatar               VARCHAR(200),
  game                 VARCHAR(40),
  user_count           INTEGER(11),
  live_time            DATETIME,
  create_time          DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time          DATETIME ON UPDATE CURRENT_TIMESTAMP
)
  DEFAULT CHARSET UTF8MB4